layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    # projects:
    # - repo-name

# social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: MagicPuddle
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  website: https://magicpuddle.netlify.app
  # youtube: your_username

topics:
  - name: Makers
    web_url: https://github.com/topics/makers
    mage_url: https://www.teachhub.com/wp-content/uploads/2020/06/What-is-Maker-Education-768x512.jpg
    
  - name: freeBSD
    web_url: https://github.com/topics/freebsd
    image_url: https://d15shllkswkct0.cloudfront.net/wp-content/blogs.dir/1/files/2015/01/freebsd-devil-284x300.jpg

  - name: Darwin
    web_url: https://github.com/topics/darwin
    image_url: https://avatars.githubusercontent.com/u/10107359?s=200&v=4
